[[snippets]]
  Description = "Check what listens on a port using netstat"
  Output = ""
  Tag = ["network", "linux"]
  command = "sudo netstat -pnltu | grep <port=8080>"

[[snippets]]
  Description = "Get encoded csr in a proper format"
  Output = "Token ready to be pasted in the token field of Kubernetes dashboard for example."
  Tag = ["kubernetes", "kubectl"]
  command = "cat <csr=myuser.csr> | base64 | tr -d \"\\n\""

[[snippets]]
  Description = "Find zsh alias by name, first result usually lists file where alias originates from"
  Output = "Top has files with possible aliases"
  Tag = ["linux", "command-line"]
  command = "zsh -ixc : 2>&1 | rg <alias=alias> -B 5"

[[snippets]]
  Description = "Copy path to a file to the clipboard (macOS)"
  Output = "Path to a file copied to clipboard"
  Tag = ["macos", "clipboard"]
  command = "readlink -fn <file=file.txt> | pbcopy"

[[snippets]]
  Description = "Git show all changes commits to a file, helpful for tracking changes"
  Output = ""
  Tag = ["git", "commit"]
  command = "git log --follow --stat -p -- <file=file.txt>"

[[snippets]]
  Description = "Check if branch is eligible for merge"
  Output = ""
  Tag = ["git"]
  command = "git merge --no-commit --no-ff <branch=feature-branch> && echo $? && git merge --abort"

[[snippets]]
  Description = "Git list branches not merged with origin main"
  Output = ""
  Tag = ["git"]
  command = "git branch --no-merged origin/main"

[[snippets]]
  Description = "Git list branches merged with origin main"
  Output = ""
  Tag = ["git"]
  command = "git branch --merged origin/main"

[[snippets]]
  Description = "Paste content copied from clipboard to a file (macOS)"
  Output = ""
  Tag = ["macos", "clipboard"]
  command = "pbpaste >> <file=output.txt>"

[[snippets]]
  Description = "Git find deleted files and show their commits. Helpful when needing to undelete a file."
  Output = ""
  Tag = ["git"]
  command = "git log --diff-filter=D --summary | grep -E 'delete|^commit\\s+\\S+'"

[[snippets]]
  Description = "Paste yaml from clipboard and apply with kubectl (macOS)"
  Output = ""
  Tag = ["kubectl", "macos"]
  command = "pbpaste | kubectl apply -f -"

[[snippets]]
  Description = "Search git commit history content"
  Output = ""
  Tag = ["git"]
  command = "git log -p --all -G '<search_term=pattern>'"

[[snippets]]
  Description = "Link to SSH Cheat Sheet"
  Output = ""
  Tag = ["link"]
  command = "open https://www.marcobehler.com/guides/ssh-cheat-sheet"

[[snippets]]
  Description = "Git compare diff between main and current branch"
  Output = ""
  Tag = ["git"]
  command = "git diff main...$(git branch | sed -n -e 's/^\\* \\(.*\\)/\\1/p')"

[[snippets]]
  Description = "Link to Vim fix for go files when folds are closed on save"
  Output = ""
  Tag = ["link"]
  command = "open https://stackoverflow.com/a/55327996"

[[snippets]]
  Description = "Link to At reminder times table, formats execution"
  Output = ""
  Tag = ["link"]
  command = "open 'https://www.dummies.com/article/technology/computers/operating-systems/linux/how-to-schedule-jobs-in-linux-at-and-crontab-commands-255842/#:~:text=Formats%20for%20the%20at%20Command%20for%20the%20Time%20of%20Execution'"

[[snippets]]
  Description = "Link to bash conditional operators"
  Output = ""
  Tag = ["link", "nvim"]
  command = "open 'https://www.gnu.org/software/bash/manual/html_node/Bash-Conditional-Expressions.html#:~:text=6.4%20bash%20conditional%20expressions'"

[[snippets]]
  Description = "SSH generate ecdsa key in the ssh folder"
  Output = ""
  Tag = ["ssh"]
  command = "ssh-keygen -t ecdsa -f ~/.ssh/<key_name=argo_infra_rsa>"

[[snippets]]
  Description = "Fix sealed secret error cannot fetch certificate"
  Output = ""
  Tag = ["kubectl"]
  command = "kubectl -n kube-system patch svc sealed-secrets-controller --type='json' -p='[{\"op\": \"remove\", \"path\": \"/spec/ports/0/name\"}, {\"op\": \"replace\", \"path\": \"/spec/ports/0/targetPort\", \"value\":8080}]'"

[[snippets]]
  Description = "Git copy file from source branch to current branch"
  Output = ""
  Tag = ["git"]
  command = "git checkout <source_branch=main> <path_to_file=path/to/file.txt>"

[[snippets]]
  Description = "Launch program on file change. In this case kubectl apply"
  Output = ""
  Tag = ["kubectl", "linux"]
  command = "ls *.yaml | entr -s 'kubectl apply -f /dev/stdin'"

[[snippets]]
  Description = "Show colorized directory tree 2 levels deep with less"
  Output = ""
  Tag = ["linux"]
  command = "tree -LC 2 --si --sort name | less -R"

[[snippets]]
  Description = "Generate simple git changelog"
  Output = ""
  Tag = ["git"]
  command = "git log --pretty=\"- %s\" | grep -v Merge"

[[snippets]]
  Description = "git synchronize local fork origin with remote upstream"
  Output = ""
  Tag = ["git"]
  command = "git merge upstream/master"

[[snippets]]
  Description = "cleanup journalctl old logs"
  Output = ""
  Tag = ["linux"]
  command = "sudo journalctl --vacuum-size=10M"

[[snippets]]
  Description = "Link to bash pitfalls"
  Output = ""
  Tag = ["link"]
  command = "open http://mywiki.wooledge.org/BashPitfalls"

[[snippets]]
  Description = "copy your public key to your server"
  Output = ""
  Tag = ["linux", "ssh"]
  command = "ssh-copy-id <username=remote_username>@<server_ip=server_ip_address>"

[[snippets]]
  Description = "Concatenate various files including file name"
  Output = ""
  Tag = ["linux"]
  command = "tail -n +1 <file1=file1.txt> <file2=file2.txt>"

[[snippets]]
  Description = "Compare diff files listing ls between two folders"
  Output = ""
  Tag = ["linux"]
  command = "diff -rq <folder1=folder1> <folder2=folder2> | grep -E 'Only in|differ'"

[[snippets]]
  Description = "List all registered zle commands zsh shell"
  Output = ""
  Tag = ["zsh"]
  command = "zle -al"

[[snippets]]
  Description = "Extract kubeconfig from secret"
  Output = ""
  Tag = ["kubectl"]
  command = "kubectl get secret <secret=aks-secret-name> -n <namespace=upbound-system> -o jsonpath=\"{.data.kubeconfig}\" | base64 --decode"

[[snippets]]
  Description = "Git find commit where branch was created from main"
  Output = ""
  Tag = ["git"]
  command = "git merge-base main HEAD"

[[snippets]]
  Description = "kubectl get all latest events sorted by timestamp and with custom columns"
  Output = ""
  Tag = ["kubernetes", "kubectl"]
  command = "kubectl get events --all-namespaces --field-selector type=Warning -o custom-columns=TIME:.lastTimestamp,NAMESPACE:.metadata.namespace,NAME:.involvedObject.name,KIND:.involvedObject.kind,NODE:.source.host,REASON:.reason,MESSAGE:.message"

[[snippets]]
  Description = "kubectl get top nodes sorted by cpu utilization"
  Output = ""
  Tag = ["kubernetes", "kubectl"]
  command = "kubectl top nodes --sort-by=cpu"

[[snippets]]
  Description = "Show all non running pods kubectl kubernetes"
  Output = ""
  Tag = ["kubernetes", "kubectl"]
  command = "kubectl get pods --all-namespaces --field-selector 'status.phase!=Running' | grep -vi completed"

[[snippets]]
  Description = "kubectl top usage by cpu per pod per container kubernetes"
  Output = ""
  Tag = ["kubernetes", "kubectl"]
  command = "kubectl top pod --sort-by cpu --containers -A"

[[snippets]]
  Description = "docker build image with buildx and load to local images from cache"
  Output = ""
  Tag = ["docker", "buildx"]
  command = "docker build . --progress=plain --tag <tag=runtime> --load"

[[snippets]]
  Description = "Link to client-go-examples for kubectl"
  Output = ""
  Tag = ["web", "link"]
  command = "open \"https://github.com/iximiuz/client-go-examples\""

[[snippets]]
  Description = "list all images loaded on a kubernetes cluster"
  Output = ""
  Tag = ["kubectl"]
  command = "kubectl get pods -A -o jsonpath=\"{..image}\" | tr -s '[[:space:]]' '\\n' | sort | uniq -c"

[[snippets]]
  Description = "run debug container and attach to a pod's container"
  Output = ""
  Tag = ["kubernetes", "kubectl", "debug"]
  command = "kubectl -n <namespace=upbound-system> debug -it <pod=pod-name> --image=ghcr.io/superbrothers/debug --target=<container=container-name>"

[[snippets]]
  Description = "Install latest crossplane CLI"
  Output = ""
  Tag = ["crossplane"]
  command = "curl -sL \"https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh\" | sh"

[[snippets]]
  Description = "Build statically linked crossplane-cli for killercoda scenario"
  Output = ""
  Tag = ["go", "crossplane"]
  command = "CGO_ENABLED=0 go build -a -installsuffix cgo -o crossplane-cli ."

[[snippets]]
  Description = "Show my public IP address"
  Output = ""
  Tag = ["network"]
  command = "curl ifconfig.me"

[[snippets]]
  Description = "launch helm dashboard on 8080"
  Output = ""
  Tag = ["helm", "dashboard"]
  command = "helm dashboard"

[[snippets]]
  Description = "Link to Certificates tracing tool"
  Output = ""
  Tag = ["link"]
  command = "open \"https://crt.sh/\""

[[snippets]]
  Description = "Link to helm charts repository artifacthub"
  Output = ""
  Tag = ["link"]
  command = "open \"https://artifacthub.io/\""

[[snippets]]
  Description = "nslookup and dig records for a site"
  Output = "DNS records"
  Tag = ["network"]
  command = "nslookup -type=<record=ns> <subdomain=app.>cloudrumble.net && dig <record=ns> <subdomain=app.>cloudrumble.net"

[[snippets]]
  Description = "Link to local development certificates anchor"
  Output = ""
  Tag = ["link"]
  command = "open \"https://anchor.dev/\""

[[snippets]]
  Description = "run internet speed test from command line"
  Output = ""
  Tag = ["network"]
  command = "speedtest-cli"

[[snippets]]
  Description = "Link to zsh-tips-tricks"
  Output = ""
  Tag = ["web", "link"]
  command = "open \"https://strcat.de/zsh/#tipps\""

[[snippets]]
  Description = "Link to Really cool blog valuable dev"
  Output = ""
  Tag = ["web", "link"]
  command = "open \"https://thevaluable.dev/post/\""

[[snippets]]
  Description = "show ip interfaces with names and ip addresses"
  Output = ""
  Tag = ["network"]
  command = "ip -br -c a"

[[snippets]]
  Description = "Rollout restart a Kubernetes deployment"
  Output = ""
  Tag = ["kubectl"]
  command = "kubectl rollout -n <namespace=default> restart deployment <deployment=my-service>"

[[snippets]]
  Description = "Rollout restart a Kubernetes StatefulSet"
  Output = ""
  Tag = ["kubectl"]
  command = "kubectl rollout -n <namespace=default> restart statefulset <sts=my-sts>"

[[snippets]]
  Description = "Scale a Kubernetes deployment to a specific replica count"
  Output = ""
  Tag = ["kubectl", "k8s", "scale"]
  command = "kubectl scale -n <namespace=default> --replicas=<replicas=1> deploy/<deploy=my-service>"

[[snippets]]
  Description = "Transform OpenFGA DSL model file to JSON format"
  Output = ""
  Tag = ["fga"]
  command = "fga model transform --file=<file=model1.fga> --output-format=json"

[[snippets]]
  Description = "Kubectl port-forward to a dynamically selected Kong data plane pod (Blue/Green)"
  command = "kubectl port-forward $(kubectl get pods -l app=kong-dataplane<color=green>-kong -n <namespace=api-gateway> -o jsonpath='{.items[0].metadata.name}') <local_port=8100>:<pod_port=8100> -n <namespace=api-gateway>"
  Tag = ["k8s", "kubectl", "kong", "sre"]
  Output = ""

[[snippets]]
  Description = "Get unique vulnerable packages and fix versions from a Trivy JSON report"
  command = '''jq -r '.Results[].Vulnerabilities[]? | .PkgName + ": " + .InstalledVersion + " -> " + (.FixedVersion | tostring)' <trivy_report=> | sort -u'''
  Tag = ["trivy", "jq", "security", "sre"]
  Output = ""
